<a href="https://colab.research.google.com/github/space-debris/MultipleLinearRegression/blob/main/MultiLinearReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data preprocessing

In [25]:
import numpy as np
import pandas as pd

Importing dataset

In [26]:
dataset = pd.read_csv("https://raw.githubusercontent.com/space-debris/MultipleLinearRegression/main/Housepricing.csv")
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]

In [33]:
print(X)

[[0.0 1.0 0.0 0.0 0.0 1.0 2100 3 2 2 2005]
 [1.0 0.0 0.0 1.0 0.0 0.0 1600 3 2 1 1998]
 [0.0 0.0 1.0 0.0 0.0 1.0 2400 4 3 2 2010]
 [0.0 1.0 0.0 1.0 0.0 0.0 1416 2 1 1 1995]
 [1.0 0.0 0.0 0.0 1.0 0.0 3000 4 3 2 2015]
 [0.0 0.0 1.0 0.0 0.0 1.0 1985 4 2 2 2000]
 [0.0 1.0 0.0 0.0 1.0 0.0 1534 3 2 2 2002]
 [1.0 0.0 0.0 1.0 0.0 0.0 1427 3 2 1 1997]
 [0.0 1.0 0.0 1.0 0.0 0.0 1380 3 1 1 1998]
 [0.0 0.0 1.0 0.0 1.0 0.0 1494 3 2 2 2018]
 [0.0 1.0 0.0 0.0 0.0 1.0 2100 3 2 2 2003]
 [1.0 0.0 0.0 1.0 0.0 0.0 1750 3 2 1 2001]
 [0.0 0.0 1.0 0.0 0.0 1.0 2600 4 3 2 2009]
 [0.0 1.0 0.0 1.0 0.0 0.0 1578 2 1 1 1996]
 [1.0 0.0 0.0 0.0 1.0 0.0 3150 4 3 2 2016]
 [0.0 0.0 1.0 0.0 0.0 1.0 2020 4 2 2 2004]
 [0.0 1.0 0.0 0.0 1.0 0.0 1685 3 2 2 2008]
 [1.0 0.0 0.0 1.0 0.0 0.0 1465 3 1 1 1999]
 [0.0 1.0 0.0 1.0 0.0 0.0 1590 3 2 1 1996]
 [0.0 0.0 1.0 0.0 1.0 0.0 1680 3 2 2 2019]
 [0.0 1.0 0.0 0.0 0.0 1.0 1850 3 2 2 2012]
 [1.0 0.0 0.0 1.0 0.0 0.0 2250 4 2 2 2014]
 [0.0 0.0 1.0 0.0 0.0 1.0 2700 4 3 2 2007]
 [0.0 1.0 0

Encoding categorical data

In [65]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
col_trans = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[5])],remainder='passthrough')
X = np.array(col_trans.fit_transform(X))







In [42]:
col_trans = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[8])],remainder='passthrough')
X = np.array(col_trans.fit_transform(X))

Splitting the dataset into train and test sets.

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=98312)

Training the model on training set

In [44]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

Predictions

In [45]:
Y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
Y_pred = np.array(Y_pred)
Y_test = np.array(Y_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[412905.93 410000.  ]
 [298271.59 295000.  ]
 [258426.15 270000.  ]
 [306383.89 305000.  ]
 [250389.99 240000.  ]
 [347266.73 370000.  ]
 [401670.57 410000.  ]
 [358452.1  350000.  ]
 [205381.95 210000.  ]
 [270792.4  265000.  ]
 [271213.93 295000.  ]]
